# This workflow runs on push to the HackEngine Github repo

name: Push - 3.0

on: push

jobs:
  build:
    name: Push
    runs-on: ubuntu-latest
    steps:
    - name: Install yardoc
      run: |
        sudo gem install yard
    - name: Run yardoc
      run: yardoc
    - name: View files
      run: ls -R
    